name: essrezepte
favicon: null
layout_spectrum: 0.90749
typography_spectrum: 0
title: Essrezepte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74815722-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1413'
    - '#829d66'
    - '#1e6b61'
    - '#bbc388'
    - '#77b7b5'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
