name: essrezepte
favicon: null
layout_spectrum: 0.8708561279345304
typography_spectrum: 0.26392515329644084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7801818063016981
  lightness: 0.05833794199861586
  saturation: 0.1611303286626935
  rhythmicContrast: 0.11732926615513861
purpose: []
