name: essrezepte
favicon: null
layout_spectrum: 0.6734
typography_spectrum: 0.37765
title: Essrezepte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b0a7a0'
    - '#5c5a5d'
    - '#050505'
    - '#89807b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
