typography_spectrum: 0.8142186356708407
color:
  brandColors:
    - '#04050a'
    - '#fffcff'
    - '#8d0d24'
    - '#856a61'
    - '#c1a37f'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53468
analytics:
  google: UA-74815722-1
  facebook: null
  twitter: null
name: essrezepte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Fischiges
    id: 8172d620-f39e-414e-95a9-68fe033068b8
    type: content
favicon: null
title: Essrezepte
description: '  '
purpose: []
