name: essrezepte
favicon: null
layout_spectrum: 0.85353
typography_spectrum: 0.26392515329644084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79746e'
    - '#1e1818'
    - '#fafbff'
    - '#d3d2d7'
    - '#caa072'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.1611303286626935
  rhythmicContrast: 0.5
purpose: []
