typography_spectrum: 0.8142186356708407
color:
  brandColors:
    - '#04050a'
    - '#fffcff'
    - '#8d0d24'
    - '#856a61'
    - '#c1a37f'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53468
analytics:
  google: UA-74815722-1
  facebook: null
  twitter: null
name: essrezepte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Fischiges
    id: d5fc7e08-d536-40a4-b0dc-550c3c699bcd
    type: content
favicon: null
title: Essrezepte
description: '  '
purpose: []
