name: essrezepte
favicon: null
layout_spectrum: 0.09246
typography_spectrum: 0.18497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160a0a'
    - '#fcfdff'
    - '#79726c'
    - '#713721'
    - '#3c5c10'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.1611303286626935
  rhythmicContrast: 0.5
purpose: []
