name: essrezepte
favicon: null
layout_spectrum: 0.22062
typography_spectrum: 0.54913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020204'
    - '#810318'
    - '#4f6e8b'
    - '#a7a491'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
