name: essrezepte
favicon: null
layout_spectrum: 0.1869
typography_spectrum: 0
title: Essrezepte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04050a'
    - '#fffcff'
    - '#8d0d24'
    - '#856a61'
    - '#c1a37f'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
