typography_spectrum: 0.8812117318157107
color:
  brandColors:
    - '#04050a'
    - '#fffcff'
    - '#8d0d24'
    - '#856a61'
    - '#c1a37f'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53468
analytics:
  google: UA-74815722-1
  facebook: null
  twitter: null
name: essrezepte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Süsses
    id: 3bd039ad-39e1-4ecb-8366-2cb0c15a7fc8
    type: content
  - name: Fleischiges
    id: 79f0e40e-9028-4f2b-a267-b93c526714f6
    type: content
  - name: Fischiges
    id: 3cb7936a-436a-44ce-a0f4-3f0221dd2d4a
    type: content
  - name: Vegetarisches
    id: 6a2b7f60-55bd-430b-a307-751a47abb550
    type: content
favicon: null
title: ''
description: Essrezepte
purpose: []
