name: essrezepte
favicon: null
layout_spectrum: 0.22062
typography_spectrum: 0.54913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160a0a'
    - '#fcfdff'
    - '#79726c'
    - '#713721'
    - '#3c5c10'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
